### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ajinsunny**
Wiki link restored to GitHub platform

### CODE REVIEW

**Comment by ajinsunny** [comment]
Approved

**Review by ajinsunny — COMMENTED** [review]
Approve the change

**Review by JonathanAlbertMorales — APPROVED** [review]

**Review by JonathanAlbertMorales — APPROVED** [review]

**Review by JonathanAlbertMorales — APPROVED** [review]
LGTM

**Comment by ajinsunny** [comment]
LGTM

**Pull request merged**
